---
- name: Configure the web server(s) according to specs
  hosts: web
  gather_facts: true
  become: true
  roles:
    - webserver

- name: Configure the database server(s) according to specs
  hosts: db
  become: true
  roles:
    - dbserver
  vars_files:
    - vars/dbvault.yml
