---
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present
    # changed from latest to present to make it production-level

- name: Ensure nginx is enabled at boot
  ansible.builtin.service:
    name: nginx
    enabled: true

- name: Ensure nginx is started
  ansible.builtin.service:
    name: nginx
    state: started

- name: Copy nginx https conf to webserver
  ansible.builtin.copy:
    src: https.conf
    dest: /etc/nginx/conf.d/https.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx

- name: Copy nginx example.internal configuration to webserver (TEMPLATE)
  ansible.builtin.template:
    src: example.internal.conf.j2
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx

- name: Create directory structure
  ansible.builtin.file:
    path: /var/www/example.internal/html/
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  notify:
    - Reload nginx

- name: Copy index.html into web root
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/example.internal/html/index.html
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx

- name: Adding users to groups
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    comment: "{{ item.realname }}"
    state: present
  loop:
    - {name: "alovelace", groups: ["wheel,audio,video"], realname: "Ada Lovelace", password: "$6$rounds=656000$mysecretsalt$.eNM1ZJfq/ia987d11Zo4PGvKRbL7zwWqsxKBpLGGtTmt8bqmWECBvMYHW8grUoSYqkuFLLQjyWzti3fUvMKy/" }
    - {name: "ghopper", groups: ["wheel,audio"], realname: "Grace Hopper", password: "$6$rounds=656000$mysecretsalt1$0NqUirlWOs5ERlHzR/0u0yS48p49RICictiBtMurMODai9lbeAz6B6Y2QKa/HcBFybH0bbQRsRzsbWetHS7Ab1" }
    - {name: "aturing", groups: "tape", realname: "Alan Turing", password: "$6$rounds=656000$mysecretsalt2$ReJicY/SSapugSKtvw5XN62PlQSDqGRMm/yKhx3tXIK3U4b82.DPKS.l9cZR2aOr1szg1fq.NpDXOiNmkmc4Q/" }
    - {name: "edijkstra", groups: "tcpdump", realname: "Edsger W. Dijkstra", password: "$6$rounds=656000$mysecretsalt3$m8qIPN9X.Kk6aKIn2bXl0Y8zA1ULHm5LVmMmEkrL/HJFgolVsjc9iT.d0IdmSA21Vl/AJeb6QrZBuhkKoEIuA0" }
